### ISSUE TITLE
Upgrade Go language version to 1.14

### ISSUE THREAD

**Issue by ray-milkey** [onosproject/onos-ric#148]
Keeping up with the latest go version

**Comment by SeanCondon** [comment]
This should probably start with an update to 
https://github.com/onosproject/build-tools/blob/master/build/golang-build/Dockerfile

The concern that I had was that when using go 1.14 with Intellij Idea 2019.2 I was not able to debug as the version of "delve" required 1.13 at the most.

The reason for using 2019.2 is because the is still the recommended version for ONOS classic Bazel. See:
https://wiki.onosproject.org/pages/viewpage.action?pageId=28836246
